return {
[1]   =  {maneuver="fire",name="Strobe",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[2]   =  {maneuver="fire",name="Tension Spring",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[3]   =  {maneuver="fire",name="Inhibitor",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[4]   =  {maneuver="fire",name="Tension Spring II",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[5]   =  {maneuver="fire",name="Attuner",family="Attuner",has_ability=false,incoming_text="",recast=0},
[6]   =  {maneuver="fire",name="Reactive Shield",family="Reactive Shield",has_ability=true,incoming_text="Unknown",recast=65},
[7]   =  {maneuver="fire",name="Flame Holder",family="Flame Holder",has_ability=false,incoming_text="",recast=0},
[8]   =  {maneuver="fire",name="Heat Capacitor",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[9]   =  {maneuver="fire",name="Strobe II",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[10]  =  {maneuver="fire",name="Tension Spring III",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[11]  =  {maneuver="fire",name="Inhibitor II",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[12]  =  {maneuver="fire",name="Tension Spring IV",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[13]  =  {maneuver="fire",name="Heat Capacitor II",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[14]  =  {maneuver="fire",name="Speedloader",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[15]  =  {maneuver="fire",name="Speedloader II",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[16]  =  {maneuver="fire",name="Tension Spring V",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[17]  =  {maneuver="fire",name="Magniplug",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[18]  =  {maneuver="fire",name="Magniplug II",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[33]  =  {maneuver="ice",name="Mana Booster",family="Mana Booster",has_ability=false,incoming_text="",recast=0},
[34]  =  {maneuver="ice",name="Loudspeaker",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[35]  =  {maneuver="ice",name="Scanner",family="Scanner",has_ability=false,incoming_text="",recast=0},
[36]  =  {maneuver="ice",name="Loudspeaker II",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[37]  =  {maneuver="ice",name="Tactical Processor",family="Tactical Processor",has_ability=false,incoming_text="",recast=0},
[38]  =  {maneuver="ice",name="Tranquilizer",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[39]  =  {maneuver="ice",name="Ice Maker",family="ice Maker",has_ability=false,incoming_text="",recast=0},
[40]  =  {maneuver="ice",name="Power Cooler",family="Power Cooler",has_ability=false,incoming_text="",recast=0},
[41]  =  {maneuver="ice",name="Loudspeaker III",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[42]  =  {maneuver="ice",name="Tranquilizer II",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[43]  =  {maneuver="ice",name="Amplifier",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[44]  =  {maneuver="ice",name="Loudspeaker IV",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[45]  =  {maneuver="ice",name="Tranquilizer III",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[46]  =  {maneuver="ice",name="Amplifier II",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[47]  =  {id=0,maneuver="ice",name="Loudspeaker V",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[48]  =  {id=0,maneuver="ice",name="Tranquilizer IV",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[49]  =  {id=0,maneuver="ice",name="Arcanoclutch",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[50]  =  {id=0,maneuver="ice",name="Arcanoclutch II",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[65]  =  {maneuver="wind",name="Accelerator",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[66]  =  {maneuver="wind",name="Scope",family="Scope",has_ability=false,incoming_text="",recast=0},
[67]  =  {maneuver="wind",name="Pattern Reader",family="Pattern Reader",has_ability=false,incoming_text="",recast=0},
[68]  =  {maneuver="wind",name="Accelerator II",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[69]  =  {maneuver="wind",name="Drum Magazine",family="Drum Magazine",has_ability=false,incoming_text="",recast=0},
[70]  =  {maneuver="wind",name="Turbo Charger",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[71]  =  {maneuver="wind",name="Replicator",family="Replicator",has_ability=true,incoming_text="Unknown",recast=60},
[72]  =  {maneuver="wind",name="Barrage Turbine",family="Barrage Turbine",has_ability=true,incoming_text="Unknown",recast=180},
[73]  =  {maneuver="wind",name="Turbo Charger II",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[74]  =  {maneuver="wind",name="Accelerator III",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[75]  =  {maneuver="wind",name="Scope II",family="Scope",has_ability=false,incoming_text="",recast=0},
[76]  =  {maneuver="wind",name="Repeater",family="Repeater",has_ability=false,incoming_text="",recast=0},
[77]  =  {maneuver="wind",name="Accelerator IV",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[78]  =  {maneuver="wind",name="Scope III",family="Scope",has_ability=false,incoming_text="",recast=0},
[79]  =  {maneuver="wind",name="Scope IV",family="Scope",has_ability=false,incoming_text="",recast=0},
[80]  =  {maneuver="wind",name="truesights",family="truesights",has_ability=false,incoming_text="",recast=0},
[97]  =  {maneuver="earth",name="Shock Absorber",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[98]  =  {maneuver="earth",name="Armor Plate",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[99]  =  {maneuver="earth",name="Analyzer",family="Analyzer",has_ability=false,incoming_text="",recast=0},
[100] =  {maneuver="earth",name="Armor Plate II",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[101] =  {maneuver="earth",name="Equalizer",family="Equalizer",has_ability=false,incoming_text="",recast=0},
[102] =  {maneuver="earth",name="Schurzen",family="Schurzen",has_ability=false,incoming_text="",recast=0},
[103] =  {maneuver="earth",name="Hammermill",family="Hammermill",has_ability=false,incoming_text="",recast=0},
[104] =  {maneuver="earth",name="Barrier Module II",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[105] =  {maneuver="earth",name="Shock Absorber II",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[106] =  {maneuver="earth",name="Armor Plate III",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[107] =  {maneuver="earth",name="Barrier Module",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[108] =  {maneuver="earth",name="Armor Plate IV",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[109] =  {maneuver="earth",name="Shock Absorber III",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[129] =  {maneuver="thunder",name="Stabilizer",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[130] =  {maneuver="thunder",name="Volt Gun",family="Volt Gun",has_ability=false,incoming_text="",recast=0},
[131] =  {maneuver="thunder",name="Heat Seeker",family="Heat Seeker",has_ability=false,incoming_text="",recast=0},
[132] =  {maneuver="thunder",name="Stabilizer II",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[133] =  {maneuver="thunder",name="Target Marker",family="Target Marker",has_ability=false,incoming_text="",recast=0},
[134] =  {maneuver="thunder",name="Dynamo",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[135] =  {maneuver="thunder",name="Coiler",family="Coiler",has_ability=false,incoming_text="",recast=0},
[136] =  {maneuver="thunder",name="Galvanizer",family="Galvanizer",has_ability=false,incoming_text="",recast=0},
[137] =  {maneuver="thunder",name="Stabilizer III",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[138] =  {maneuver="thunder",name="Coiler II",family="Coiler",has_ability=false,incoming_text="",recast=0},
[139] =  {maneuver="thunder",name="Dynamo II",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[140] =  {maneuver="thunder",name="Stabilizer IV",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[141] =  {maneuver="thunder",name="Dynamo III",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[142] =  {maneuver="thunder",name="Stabilizer V",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[161] =  {maneuver="water",name="Mana Jammer",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[162] =  {maneuver="water",name="Heatsink",family="Heatsink",has_ability=false,incoming_text="",recast=0},
[163] =  {maneuver="water",name="Stealth Screen",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[164] =  {maneuver="water",name="Mana Jammer II",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[165] =  {maneuver="water",name="Mana Channeler",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[166] =  {maneuver="water",name="Condenser",family="Condenser",has_ability=false,incoming_text="",recast=0},
[167] =  {maneuver="water",name="Steam Jacket",family="Steam Jacket",has_ability=false,incoming_text="",recast=0},
[168] =  {maneuver="water",name="Percolator",family="Percolator",has_ability=false,incoming_text="",recast=0},
[169] =  {maneuver="water",name="Mana Jammer III",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[170] =  {maneuver="water",name="Stealth Screen II",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[171] =  {maneuver="water",name="Resister",family="Resister",has_ability=false,incoming_text="",recast=0},
[172] =  {maneuver="water",name="Resister II",family="Resister",has_ability=false,incoming_text="",recast=0},
[173] =  {maneuver="water",name="Mana Jammer IV",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[174] =  {maneuver="water",name="Mana Channeler II",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[193] =  {maneuver="light",name="Auto-Repair Kit",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[194]  =  {id=0,maneuver="light",name="Flashbulb",family="Flashbulb",has_ability=true,incoming_text="Flashbulb",recast=45},
[195]  =  {id=0,maneuver="light",name="Damage Gauge",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[196]  =  {id=0,maneuver="light",name="Auto-Repair Kit II",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[197]  =  {id=0,maneuver="light",name="Eraser",family="Eraser",has_ability=true,incoming_text="Unknown",recast=30},
[198] =  {id=1,maneuver="light",name="Optic Fiber",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[200] =  {id=0,maneuver="light",name="Vivi-Valve",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[201] =  {id=0,maneuver="light",name="Vivi-Valve II",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[202] =  {id=0,maneuver="light",name="Auto-Repair Kit III",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[203] =  {id=0,maneuver="light",name="Arcanic Cell",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[204] =  {id=0,maneuver="light",name="Arcanic Cell II",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[205] =  {id=1,maneuver="light",name="Auto-Repair Kit IV",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[206] =  {id=1,maneuver="light",name="Optic Fiber II",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[207] =  {id=0,maneuver="light",name="Damage Gauge II",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[225] =  {id=0,maneuver="dark",name="Mana Tank",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[226] =  {id=0,maneuver="dark",name="Mana Converter",family="Mana Converter",has_ability=true,incoming_text="Unknown",recast=180},
[227] =  {id=0,maneuver="dark",name="Mana Conserver",family="Mana Conserver",has_ability=false,incoming_text="",recast=0},
[228] =  {id=0,maneuver="dark",name="Mana Tank II",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[229] =  {id=0,maneuver="dark",name="Smoke Screen",family="Smoke Screen",has_ability=false,incoming_text="",recast=0},
[230] =  {id=0,maneuver="dark",name="Economizer",family="Economizer",has_ability=true,incoming_text="Unknown",recast=180},
[232] =  {id=0,maneuver="dark",name="Disruptor",family="Disruptor",has_ability=true,incoming_text="Unknown",recast=60},
[233] =  {id=0,maneuver="dark",name="Mana Tank III",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[234] =  {id=0,maneuver="dark",name="Regulator",family="Regulator",has_ability=false,incoming_text="",recast=0},
[235] =  {id=0,maneuver="dark",name="Mana Tank IV",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
}