return {
[1]   =  {id=0,maneuver="Fire Maneuver",name="Strobe",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[2]   =  {id=0,maneuver="Fire Maneuver",name="Tension Spring",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[3]   =  {id=0,maneuver="Fire Maneuver",name="Inhibitor",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[4]   =  {id=0,maneuver="Fire Maneuver",name="Tension Spring II",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[5]   =  {id=0,maneuver="Fire Maneuver",name="Attuner",family="Attuner",has_ability=false,incoming_text="",recast=0},
[6]   =  {id=0,maneuver="Fire Maneuver",name="Reactive Shield",family="Reactive Shield",has_ability=true,incoming_text="Unknown",recast=65},
[7]   =  {id=0,maneuver="Fire Maneuver",name="Flame Holder",family="Flame Holder",has_ability=false,incoming_text="",recast=0},
[8]   =  {id=0,maneuver="Fire Maneuver",name="Heat Capacitor",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[9]   =  {id=0,maneuver="Fire Maneuver",name="Strobe II",family="Strobe",has_ability=true,incoming_text="Provoke",recast=30},
[10]  = {id=0,maneuver="Fire Maneuver",name="Tension Spring III",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[11]  = {id=0,maneuver="Fire Maneuver",name="Inhibitor II",family="Inhibitor",has_ability=false,incoming_text="",recast=0},
[12]  = {id=0,maneuver="Fire Maneuver",name="Tension Spring IV",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[13]  = {id=0,maneuver="Fire Maneuver",name="Heat Capacitor II",family="Heat Capacitor",has_ability=true,incoming_text="Unknown",recast=90},
[14]  = {id=0,maneuver="Fire Maneuver",name="Speedloader",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[15]  = {id=0,maneuver="Fire Maneuver",name="Speedloader II",family="Speedloader",has_ability=false,incoming_text="",recast=0},
[16]  = {id=0,maneuver="Fire Maneuver",name="Tension Spring V",family="Tension Spring",has_ability=false,incoming_text="",recast=0},
[17]  = {id=0,maneuver="Fire Maneuver",name="Magniplug",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[18]  = {id=0,maneuver="Fire Maneuver",name="Magniplug II",family="Magniplug",has_ability=false,incoming_text="",recast=0},
[19]  = {id=0,maneuver="Ice Maneuver",name="Mana Booster",family="Mana Booster",has_ability=false,incoming_text="",recast=0},
[20]  = {id=0,maneuver="Ice Maneuver",name="Loudspeaker",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[21]  = {id=0,maneuver="Ice Maneuver",name="Scanner",family="Scanner",has_ability=false,incoming_text="",recast=0},
[22]  = {id=0,maneuver="Ice Maneuver",name="Loudspeaker II",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[23]  = {id=0,maneuver="Ice Maneuver",name="Tactical Processor",family="Tactical Processor",has_ability=false,incoming_text="",recast=0},
[24]  = {id=0,maneuver="Ice Maneuver",name="Tranquilizer",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[25]  = {id=0,maneuver="Ice Maneuver",name="Ice Maker",family="Ice Maker",has_ability=false,incoming_text="",recast=0},
[26]  = {id=0,maneuver="Ice Maneuver",name="Power Cooler",family="Power Cooler",has_ability=false,incoming_text="",recast=0},
[27]  = {id=0,maneuver="Ice Maneuver",name="Loudspeaker III",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[28]  = {id=0,maneuver="Ice Maneuver",name="Tranquilizer II",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[29]  = {id=0,maneuver="Ice Maneuver",name="Amplifier",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[30]  = {id=0,maneuver="Ice Maneuver",name="Loudspeaker IV",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[31]  = {id=0,maneuver="Ice Maneuver",name="Tranquilizer III",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[32]  = {id=0,maneuver="Ice Maneuver",name="Amplifier II",family="Amplifier",has_ability=false,incoming_text="",recast=0},
[33]  = {id=0,maneuver="Ice Maneuver",name="Loudspeaker V",family="Loudspeaker",has_ability=false,incoming_text="",recast=0},
[34]  = {id=0,maneuver="Ice Maneuver",name="Tranquilizer IV",family="Tranquilizer",has_ability=false,incoming_text="",recast=0},
[35]  = {id=0,maneuver="Ice Maneuver",name="Arcanoclutch",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[36]  = {id=0,maneuver="Ice Maneuver",name="Arcanoclutch II",family="Arcanoclutch",has_ability=false,incoming_text="",recast=0},
[37]  = {id=0,maneuver="Wind Maneuver",name="Accelerator",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[38]  = {id=0,maneuver="Wind Maneuver",name="Scope",family="Scope",has_ability=false,incoming_text="",recast=0},
[39]  = {id=0,maneuver="Wind Maneuver",name="Pattern Reader",family="Pattern Reader",has_ability=false,incoming_text="",recast=0},
[40]  = {id=0,maneuver="Wind Maneuver",name="Accelerator II",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[41]  = {id=0,maneuver="Wind Maneuver",name="Drum Magazine",family="Drum Magazine",has_ability=false,incoming_text="",recast=0},
[42]  = {id=0,maneuver="Wind Maneuver",name="Turbo Charger",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[43]  = {id=0,maneuver="Wind Maneuver",name="Replicator",family="Replicator",has_ability=true,incoming_text="Unknown",recast=60},
[44]  = {id=0,maneuver="Wind Maneuver",name="Barrage Turbine",family="Barrage Turbine",has_ability=true,incoming_text="Unknown",recast=180},
[45]  = {id=0,maneuver="Wind Maneuver",name="Turbo Charger II",family="Turbo Charger",has_ability=false,incoming_text="",recast=0},
[46]  = {id=0,maneuver="Wind Maneuver",name="Accelerator III",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[47]  = {id=0,maneuver="Wind Maneuver",name="Scope II",family="Scope",has_ability=false,incoming_text="",recast=0},
[48]  = {id=0,maneuver="Wind Maneuver",name="Repeater",family="Repeater",has_ability=false,incoming_text="",recast=0},
[49]  = {id=0,maneuver="Wind Maneuver",name="Accelerator IV",family="Accelerator",has_ability=false,incoming_text="",recast=0},
[50]  = {id=0,maneuver="Wind Maneuver",name="Scope III",family="Scope",has_ability=false,incoming_text="",recast=0},
[51]  = {id=0,maneuver="Wind Maneuver",name="Scope IV",family="Scope",has_ability=false,incoming_text="",recast=0},
[52]  = {id=0,maneuver="Wind Maneuver",name="truesights",family="truesights",has_ability=false,incoming_text="",recast=0},
[53]  = {id=0,maneuver="Earth Maneuver",name="Shock Absorber",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[54]  = {id=0,maneuver="Earth Maneuver",name="Armor Plate",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[55]  = {id=0,maneuver="Earth Maneuver",name="Analyzer",family="Analyzer",has_ability=false,incoming_text="",recast=0},
[56]  = {id=0,maneuver="Earth Maneuver",name="Armor Plate II",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[57]  = {id=0,maneuver="Earth Maneuver",name="Equalizer",family="Equalizer",has_ability=false,incoming_text="",recast=0},
[58]  = {id=0,maneuver="Earth Maneuver",name="Schurzen",family="Schurzen",has_ability=false,incoming_text="",recast=0},
[59]  = {id=0,maneuver="Earth Maneuver",name="Hammermill",family="Hammermill",has_ability=false,incoming_text="",recast=0},
[60]  = {id=0,maneuver="Earth Maneuver",name="Barrier Module II",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[61]  = {id=0,maneuver="Earth Maneuver",name="Shock Absorber II",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[62]  = {id=0,maneuver="Earth Maneuver",name="Armor Plate III",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[63]  = {id=0,maneuver="Earth Maneuver",name="Barrier Module",family="Barrier Module",has_ability=true,incoming_text="Unknown",recast=180},
[108] = {id=1,maneuver="Earth Maneuver",name="Armor Plate IV",family="Armor Plate",has_ability=false,incoming_text="",recast=0},
[65]  = {id=0,maneuver="Earth Maneuver",name="Shock Absorber III",family="Shock Absorber",has_ability=true,incoming_text="Unknown",recast=180},
[66]  = {id=0,maneuver="Earth Maneuver",name="Stabilizer",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[67]  = {id=0,maneuver="Thunder Maneuver",name="Volt Gun",family="Volt Gun",has_ability=false,incoming_text="",recast=0},
[68]  = {id=0,maneuver="Thunder Maneuver",name="Heat Seeker",family="Heat Seeker",has_ability=false,incoming_text="",recast=0},
[69]  = {id=0,maneuver="Thunder Maneuver",name="Stabilizer II",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[70]  = {id=0,maneuver="Thunder Maneuver",name="Target Marker",family="Target Marker",has_ability=false,incoming_text="",recast=0},
[71]  = {id=0,maneuver="Thunder Maneuver",name="Dynamo",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[72]  = {id=0,maneuver="Thunder Maneuver",name="Coiler",family="Coiler",has_ability=false,incoming_text="",recast=0},
[73]  = {id=0,maneuver="Thunder Maneuver",name="Galvanizer",family="Galvanizer",has_ability=false,incoming_text="",recast=0},
[74]  = {id=0,maneuver="Thunder Maneuver",name="Stabilizer III",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[75]  = {id=0,maneuver="Thunder Maneuver",name="Coiler II",family="Coiler",has_ability=false,incoming_text="",recast=0},
[76]  = {id=0,maneuver="Thunder Maneuver",name="Dynamo II",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[77]  = {id=0,maneuver="Thunder Maneuver",name="Stabilizer IV",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[78]  = {id=0,maneuver="Thunder Maneuver",name="Dynamo III",family="Dynamo",has_ability=false,incoming_text="",recast=0},
[79]  = {id=0,maneuver="Thunder Maneuver",name="Stabilizer V",family="Stabilizer",has_ability=false,incoming_text="",recast=0},
[80]  = {id=0,maneuver="Water Maneuver",name="Mana Jammer",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[81]  = {id=0,maneuver="Water Maneuver",name="Heatsink",family="Heatsink",has_ability=false,incoming_text="",recast=0},
[82]  = {id=0,maneuver="Water Maneuver",name="Stealth Screen",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[83]  = {id=0,maneuver="Water Maneuver",name="Mana Jammer II",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[84]  = {id=0,maneuver="Water Maneuver",name="Mana Channeler",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[85]  = {id=0,maneuver="Water Maneuver",name="Condenser",family="Condenser",has_ability=false,incoming_text="",recast=0},
[86]  = {id=0,maneuver="Water Maneuver",name="Steam Jacket",family="Steam Jacket",has_ability=false,incoming_text="",recast=0},
[87]  = {id=0,maneuver="Water Maneuver",name="Percolator",family="Percolator",has_ability=false,incoming_text="",recast=0},
[88]  = {id=0,maneuver="Water Maneuver",name="Mana Jammer III",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[89]  = {id=0,maneuver="Water Maneuver",name="Stealth Screen II",family="Stealth Screen",has_ability=false,incoming_text="",recast=0},
[90]  = {id=0,maneuver="Water Maneuver",name="Resister",family="Resister",has_ability=false,incoming_text="",recast=0},
[91]  = {id=0,maneuver="Water Maneuver",name="Resister II",family="Resister",has_ability=false,incoming_text="",recast=0},
[92]  = {id=0,maneuver="Water Maneuver",name="Mana Jammer IV",family="Mana Jammer",has_ability=false,incoming_text="",recast=0},
[93]  = {id=0,maneuver="Water Maneuver",name="Mana Channeler II",family="Mana Channeler",has_ability=false,incoming_text="",recast=0},
[94]  = {id=0,maneuver="Light Maneuver",name="Auto-Repair Kit",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[95]  = {id=0,maneuver="Light Maneuver",name="Flashbulb",family="Flashbulb",has_ability=true,incoming_text="Flashbulb",recast=45},
[96]  = {id=0,maneuver="Light Maneuver",name="Damage Gauge",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[97]  = {id=0,maneuver="Light Maneuver",name="Auto-Repair Kit II",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[98]  = {id=0,maneuver="Light Maneuver",name="Eraser",family="Eraser",has_ability=true,incoming_text="Unknown",recast=30},
[198] =  {id=1,maneuver="Light Maneuver",name="Optic Fiber",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[100] =  {id=0,maneuver="Light Maneuver",name="Vivi-Valve",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[101] =  {id=0,maneuver="Light Maneuver",name="Vivi-Valve II",family="Vivi-Valve",has_ability=false,incoming_text="",recast=0},
[102] =  {id=0,maneuver="Light Maneuver",name="Auto-Repair Kit III",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[103] =  {id=0,maneuver="Light Maneuver",name="Arcanic Cell",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[104] =  {id=0,maneuver="Light Maneuver",name="Arcanic Cell II",family="Arcanic Cell",has_ability=false,incoming_text="",recast=0},
[205] =  {id=1,maneuver="Light Maneuver",name="Auto-Repair Kit IV",family="Auto-Repair Kit",has_ability=false,incoming_text="",recast=0},
[106] =  {id=0,maneuver="Light Maneuver",name="Optic Fiber II",family="Optic Fiber",has_ability=false,incoming_text="",recast=0},
[107] =  {id=0,maneuver="Light Maneuver",name="Damage Gauge II",family="Damage Gauge",has_ability=false,incoming_text="",recast=0},
[108] =  {id=0,maneuver="Dark Maneuver",name="Mana Tank",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[109] =  {id=0,maneuver="Dark Maneuver",name="Mana Converter",family="Mana Converter",has_ability=true,incoming_text="Unknown",recast=180},
[110] =  {id=0,maneuver="Dark Maneuver",name="Mana Conserver",family="Mana Conserver",has_ability=false,incoming_text="",recast=0},
[111] =  {id=0,maneuver="Dark Maneuver",name="Mana Tank II",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[112] =  {id=0,maneuver="Dark Maneuver",name="Smoke Screen",family="Smoke Screen",has_ability=false,incoming_text="",recast=0},
[113] =  {id=0,maneuver="Dark Maneuver",name="Economizer",family="Economizer",has_ability=true,incoming_text="Unknown",recast=180},
[114] =  {id=0,maneuver="Dark Maneuver",name="Disruptor",family="Disruptor",has_ability=true,incoming_text="Unknown",recast=60},
[115] =  {id=0,maneuver="Dark Maneuver",name="Mana Tank III",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
[116] =  {id=0,maneuver="Dark Maneuver",name="Regulator",family="Regulator",has_ability=false,incoming_text="",recast=0},
[117] =  {id=0,maneuver="Dark Maneuver",name="Mana Tank IV",family="Mana Tank",has_ability=false,incoming_text="",recast=0},
}