local spells = {

    {id=115, name="Firestorm",    family="Firestorm", element="fire"},
    {id=860, name="Firestorm II", family="Firestorm", element="fire"},
    {id=281, name="Pyrohelix", family="pyrohelix", element="fire"},
    {id=888, name="Pyrohelix II", family="pyrohelix", element="fire"},
    {id=144, name="Fire", family="fire", element="fire"},
    {id=145, name="Fire II", family="fire", element="fire"},
    {id=146, name="Fire III", family="fire", element="fire"},
    {id=147, name="Fire IV", family="fire", element="fire"},
    {id=148, name="Fire V", family="fire", element="fire"},

    {id=116, name="Hailstorm",    family="Hailstorm", element="ice"},
    {id=861, name="Hailstorm II", family="Hailstorm", element="ice"},
    {id=282, name="Cryohelix", family="cryohelix", element="ice"},
    {id=889, name="Cryohelix II", family="cryohelix", element="ice"},
    {id=149, name="Blizzard", family="blizzard", element="ice"},
    {id=150, name="Blizzard II", family="blizzard", element="ice"},
    {id=151, name="Blizzard III", family="blizzard", element="ice"},
    {id=152, name="Blizzard IV", family="blizzard", element="ice"},
    {id=153, name="Blizzard V", family="blizzard", element="ice"},

    {id=114, name="Windstorm",    family="Windstorm", element="wind"},
    {id=859, name="Windstorm II", family="Windstorm", element="wind"},
    {id=280, name="Anemohelix", family="anemohelix", element="wind"},
    {id=887, name="Anemohelix II", family="anemohelix", element="wind"},
    {id=154, name="Aero", family="aero", element="wind"},
    {id=155, name="Aero II", family="aero", element="wind"},
    {id=156, name="Aero III", family="aero", element="wind"},
    {id=157, name="Aero IV", family="aero", element="wind"},
    {id=158, name="Aero V", family="aero", element="wind"},

    {id=99,  name="Sandstorm",    family="Sandstorm", element="stone"},
    {id=857, name="Sandstorm II", family="Sandstorm", element="stone"},
    {id=278, name="Geohelix", family="geohelix", element="stone"},
    {id=885, name="Geohelix II", family="geohelix", element="stone"},
    {id=159, name="Stone", family="stone", element="stone"},
    {id=160, name="Stone II", family="stone", element="stone"},
    {id=161, name="Stone III", family="stone", element="stone"},
    {id=162, name="Stone IV", family="stone", element="stone"},
    {id=163, name="Stone V", family="stone", element="stone"},

    {id=117, name="Thunderstorm",    family="Thunderstorm", element="thunder"},
    {id=862, name="Thunderstorm II", family="Thunderstorm", element="thunder"},
    {id=283, name="Ionohelix", family="ionohelix", element="thunder"},
    {id=890, name="Ionohelix II", family="ionohelix", element="thunder"},
    {id=164, name="Thunder", family="thunder", element="thunder"},
    {id=165, name="Thunder II", family="thunder", element="thunder"},
    {id=166, name="Thunder III", family="thunder", element="thunder"},
    {id=167, name="Thunder IV", family="thunder", element="thunder"},
    {id=168, name="Thunder V", family="thunder", element="thunder"},

    {id=113, name="Rainstorm",    family="Rainstorm", element="water"},
    {id=858, name="Rainstorm II", family="Rainstorm", element="water"},
    {id=279, name="Hydrohelix", family="hydrohelix", element="water"},
    {id=886, name="Hydrohelix II", family="hydrohelix", element="water"},
    {id=169, name="Water", family="water", element="water"},
    {id=170, name="Water II", family="water", element="water"},
    {id=171, name="Water III", family="water", element="water"},
    {id=172, name="Water IV", family="water", element="water"},
    {id=173, name="Water V", family="water", element="water"},

    {id=118, name="Voidstorm",    family="Voidstorm", element="dark"},
    {id=863, name="Voidstorm II", family="Voidstorm", element="dark"},
    {id=284, name="Noctohelix", family="noctohelix", element="dark"},
    {id=891, name="Noctohelix II", family="noctohelix", element="dark"},

    {id=119, name="Autorastorm",    family="Autorastorm", element="light"},
    {id=864, name="Autorastorm II", family="Autorastorm", element="light"},
    {id=285, name="Luminohelix", family="luminohelix", element="light"},
    {id=892, name="Luminohelix II", family="luminohelix", element="light"},
}